apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base


patches:
- target:
    kind: Secret
    name: loki-s3
  patch: |-
    - op: replace
      path: /stringData/endpoint
      value: "http://sandbox.com"