apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - loki-object-storage.yaml  # TODO: create this secret

patches:
- target:
    kind: LokiStack
    name: lokistack
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: ocs-external-storagecluster-ceph-rbd
    - op: replace
      path: /spec/size
      value: 1x.demo

