apiVersion: v1
kind: Secret
metadata:
  name: loki-object-stroage
  namespace: openshift-logging
stringData:
  access_key_id: AWS_ACCESS_KEY_ID
  access_key_secret: AWS_ACCESS_KEY_SECRET
  bucketnames: BUCKET_NAME
  endpoint: AWS_BUCKET_ENDPOINT
