---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-collect-application-logs
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: collect-application-logs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-collect-infrastructure-logs
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: collect-infrastructure-logs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-collect-audit-logs
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: collect-audit-logs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-logging-collector-logs-writer
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: logging-collector-logs-writer
