apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- OpenShiftLogging/namespace.yaml
  - OpenShiftLogging/service-account.yaml
  - OpenShiftLogging/clusterLogForwarder.yaml
  - Loki/lokiStack.yaml
  - Loki/cluster-wide-log-access.yaml
  - ClusterObservability/UIPlugin.yaml


